#!/bin/bash
# share screenshots or screencasts of the entire screen, a window, or a region

print_usage() {
	printf "Usage:\n"
	printf "\t$(basename $0) [OPTION]...\n" # TODO this is probably the wrong syntax
	printf "\nHelp Options:\n"
	printf "\t-h\t\t\t\tPrint this help message\n"
	printf "\\nApplication Options:\n"
	printf "\t-t, --type\t\t\tCapture type\n"
	printf "\t-s, --selection\t\t\tSelection type\n"
	printf "\t-d, --destination\t\tUpload destination\n"
	printf "\t-w, --wait\t\t\tWait time\n"
	# TODO move all this to a man page or something
	printf "\nCapture types:\n"
	printf "\tscreenshot - a screenshot\n"
	printf "\tscreencast - a video recording\n" # TODO file
	printf "\nSelections:\n"
	printf "\tregion - a user-drawn region of the screen\n"
	printf "\tfocused - the currently focused window\n"
	printf "\tfull - the entire screen\n"
	printf "\nDestinations:\n"
	printf "\tclipboard - copy to the clipboard\n"
	printf "\tupload - upload using the uploader script\n"
}

finish_screencast() {
	if [[ $FFMPEG_PID -ne 0 ]]; then
		kill -15 $FFMPEG_PID
		wait $FFMPEG_PID
		share $DESTINATION < /tmp/screencast.mp4
		rm /tmp/screencast.mp4 # TODO allow preserving screenshots/casts
	fi
	exit 0
}

trap finish_screencast 10

error_exit() {
	echo "$(basename $0): ${1:-"Unknown error"}" 1>&2
}


share() {
	CONFIG_DIR=$([[ -z $XDG_CONFIG_HOME ]] && echo "$HOME/.config" || echo $XDG_CONFIG_HOME)
	case $1 in
		"clipboard")
			if [[ $TYPE != "screenshot" ]]; then
				echo "Cannot copy type $TYPE to clipboard" >&2
				exit 1
			fi
			xclip -selection clipboard -target image/png
			;;
		"upload")
			UPLOADER=$CONFIG_DIR/shshare/uploader.sh
			[[ ! -e $UPLOADER ]] && UPLOADER=/etc/shshare/uploader.sh
			case $TYPE in
				"screenshot")
					$UPLOADER image
					;;
				"screencast")
					$UPLOADER video
					;;
			esac
			;;
		*)
			if [[ -n $1 ]]; then
				error_exit "Invalid destination"
			else
				error_exit "No destination provided"
			fi
			;;
	esac
}

if [[ $# -eq 0 ]]; then
	print_usage
	exit 1
fi

TYPE=0
SELECTION=0
DESTINATION=0
WAIT=0
POSITIONAL=()

while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-t|--type)
			TYPE="$2"
			shift
			shift
			;;
		-s|--selection)
			SELECTION="$2"
			shift
			shift
			;;
		-d|--destination)
			DESTINATION="$2"
			shift
			shift
			;;
		-w|--wait)
			WAIT="$2"
			shift
			shift
			;;
		-h|--help)
			print_usage
			;;
		*)
			POSITIONAL+=("$1")
			shift
			;;
	esac
done
set -- $"{POSITIONAL[@]}"

if [[ !($WAIT =~ ^-?\.?[0-9]+$) ]]; then
	echo "Invalid delay: $WAIT"
	exit 1
fi
	

case $TYPE in
	"screenshot")
		case $SELECTION in
			"region")
				maim --delay $WAIT --select --hidecursor | share $DESTINATION
				;;
			"focused")
				maim --delay $WAIT --window=$(xdotool getactivewindow) --hidecursor | share $DESTINATION
				;;
			"full")
				maim --delay $WAIT | share $DESTINATION
				;;
		esac
		;;
	"screencast")
		if [[ $TYPE != "region" ]]; then
			echo "Unsupported screemcast selection: $TYPE" 1>&2 # if someone wants to record their entire screen they should use OBS anyway
		fi
		region=$(slop --format="%x,%y %wx%h")
		size=$(echo $region | cut -d' ' -f 2)
		offset=$(echo $region | cut -d' ' -f 1)
		sleep $WAIT
		ffmpeg \
			-video_size $size \
			-framerate 60 \
			-f x11grab \
			-i :0.0+$offset \
			-pix_fmt yuv420p \
			/tmp/screencast.mp4 \
			-vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" & # pad regions who's dimensions are not divisible by 2 for x264 encoding
		FFMPEG_PID=$!
		wait $FFMPEG_PID # keep alive so we can catch SIGUSR1 when the user wants to stop the recording
		;;
	"screencast-stop")
		killall -10 $(basename $0)
		;;
esac
